sonar.projectKey=Roger-Balcevicz_prova02-integration-test-RogerBalcevicz
sonar.organization=roger-balcevicz
sonar.projectName=Prova 02 - Integration Tests
sonar.projectVersion=1.0
sonar.sources=./test
sonar.sourceEncoding=UTF-8

# projeto so tem testes de API, nao tem codigo de aplicacao para medir cobertura
sonar.coverage.exclusions=**/*

# o sonar nao reconhece os expect do pactum (expectStatus, expectJson...) como assercao
sonar.issue.ignore.multicriteria=e1
sonar.issue.ignore.multicriteria.e1.ruleKey=typescript:S2699
sonar.issue.ignore.multicriteria.e1.resourceKey=test/**/*.spec.ts
