sonar.projectKey=Roger-Balcevicz_prova02-integration-test-RogerBalcevicz
sonar.organization=roger-balcevicz
sonar.projectName=Prova 02 - Integration Tests
sonar.projectVersion=1.0
sonar.sources=./test
sonar.sourceEncoding=UTF-8
